version: '3'

includes:
  nix-lint: ./Taskfile.nix.yml
  age: ./secrets/Taskfile.yml


# Nix-Darwin management tasks
# Converted from rich-demo Justfile with additional migration functionality

vars:
  NIX_DIR: '.'
  HOSTNAME:
    sh: scutil --get ComputerName | tr ' ' '-' | tr '[:upper:]' '[:lower:]'
  SYSTEM:
    sh: |
      if [[ $(uname -m) == "arm64" ]]; then
        echo "aarch64-darwin"
      else
        echo "x86_64-darwin"
      fi
  OS:
    sh: uname
  USERNAME:
    sh: whoami
  # Default cleanup days for maintenance tasks
  CLEANUP_DAYS: '{{.CLEANUP_DAYS | default "1"}}'
  # Nix store path
  NIX_STORE_PATH: '/nix/store'
  # System profile path
  SYSTEM_PROFILE: '/nix/var/nix/profiles/system'
  # Colors for output
  GREEN: '\033[1;32m'
  YELLOW: '\033[1;33m'
  RED: '\033[1;31m'
  NC: '\033[0m'


tasks:
  default:
    desc: "构建并切换到当前系统配置"
    cmds:
      - task: build-switch

  # === 核心构建任务 ===
  build:
    desc: "构建系统配置（不切换）"
    dir: '{{.NIX_DIR}}'
    cmds:
      - echo -e "{{.YELLOW}}正在为 {{.HOSTNAME}} ({{.SYSTEM}}) 构建 {{.OS}} 配置...{{.NC}}"
      - |
        if [[ "{{.OS}}" == "Darwin" ]]; then
          nix build .#darwinConfigurations.{{.HOSTNAME}}.system --extra-experimental-features 'nix-command flakes'
        else
          nix build .#nixosConfigurations.{{.HOSTNAME}}.config.system.build.toplevel --extra-experimental-features 'nix-command flakes'
        fi
      - echo -e "{{.GREEN}}构建完成！{{.NC}}"

  build-switch:
    desc: "构建并切换到新配置"
    dir: '{{.NIX_DIR}}'
    cmds:
      - echo -e "{{.YELLOW}}正在构建并切换 {{.OS}} 配置...{{.NC}}"
      - |
        if [[ "{{.OS}}" == "Darwin" ]]; then
          sudo darwin-rebuild switch --flake .#{{.HOSTNAME}}
        else
          sudo nixos-rebuild switch --flake .#{{.HOSTNAME}}
        fi
      - echo -e "{{.GREEN}}切换到新配置完成！{{.NC}}"

  # === 配置设置 ===
  apply:
    desc: "交互式用户配置设置（替代 apps/apply）"
    dir: '{{.NIX_DIR}}'
    interactive: true
    cmds:
      - echo "=== Nix Configuration Setup ==="
      - task: check-prerequisites
      - task: build-switch
      - echo "Configuration applied successfully!"

  check-prerequisites:
    desc: "检查系统先决条件"
    internal: true
    cmds:
      - echo "Checking prerequisites..."
      - git config --get user.name || echo "Git user.name not configured"
      - git config --get user.email || echo "Git user.email not configured"
      - which nix || echo "Nix not found in PATH"
      - echo "Prerequisites check complete"


  darwin:
    desc: "构建并切换到 nix-darwin 配置"
    dir: '{{.NIX_DIR}}'
    cmds:
      - echo -e "{{.YELLOW}}🚀 正在为 {{.HOSTNAME}} ({{.SYSTEM}}) 构建 nix-darwin 配置...{{.NC}}"
      - nix build .#darwinConfigurations.{{.HOSTNAME}}.system --extra-experimental-features 'nix-command flakes'
      - echo -e "{{.YELLOW}}🔄 正在切换到新配置...{{.NC}}"
      - sudo darwin-rebuild switch --flake .#{{.HOSTNAME}}
      - echo -e "{{.GREEN}}✅ nix-darwin 配置应用成功！{{.NC}}"

  darwin-debug:
    desc: "使用详细输出构建并切换（用于调试）"
    dir: '{{.NIX_DIR}}'
    cmds:
      - echo -e "{{.YELLOW}}🐛 正在使用调试输出构建 nix-darwin 配置...{{.NC}}"
      - nix build .#darwinConfigurations.{{.HOSTNAME}}.system --show-trace --verbose --extra-experimental-features 'nix-command flakes'
      - echo -e "{{.YELLOW}}🔄 正在使用调试输出切换...{{.NC}}"
      - sudo darwin-rebuild switch --flake .#{{.HOSTNAME}} --show-trace --verbose

  # Migration tasks (from apply-migration.sh)
  migrate:
    desc: "Apply nix-darwin migration and cleanup Homebrew packages"
    deps: [darwin]
    cmds:
      - task: cleanup-homebrew
      - task: verify-migration

  cleanup-homebrew:
    desc: "Remove packages that have been migrated to nix"
    vars:
      PACKAGES_TO_REMOVE: "go gum helm neovim fzf atuin git"
    cmds:
      - echo "🧹 Cleaning up migrated Homebrew packages..."
      - for: {var: PACKAGES_TO_REMOVE, split: ' '}
        cmd: |
          if brew list --formula | grep -q "^{{.ITEM}}$"; then
            echo "  Removing {{.ITEM}}..."
            brew uninstall "{{.ITEM}}" || echo "    Warning: Could not uninstall {{.ITEM}}"
          else
            echo "  {{.ITEM}} not installed, skipping"
          fi
      - echo "✅ Homebrew cleanup completed"

  verify-migration:
    desc: "Verify that migrated packages are working"
    vars:
      COMMANDS_TO_CHECK: "go gum helm nvim fzf atuin git"
    cmds:
      - echo "🔍 Verifying migration results..."
      - echo "Checking nix packages:"
      - for: {var: COMMANDS_TO_CHECK, split: ' '}
        cmd: |
          if command -v "{{.ITEM}}" >/dev/null 2>&1; then
            echo "  ✅ {{.ITEM}}: $(which "{{.ITEM}}")"
          else
            echo "  ❌ {{.ITEM}}: not found"
          fi
      - task: verify-shell-config
      - task: verify-system-config

  verify-shell-config:
    desc: "Verify shell configuration"
    internal: true
    cmds:
      - echo "Checking shell configuration:"
      - echo "  Current shell:" "$SHELL"
      - echo "  zsh version:" "$(zsh --version 2>/dev/null || echo 'not found')"

  verify-system-config:
    desc: "Verify system configuration"
    internal: true
    cmds:
      - echo "Checking system configuration:"
      - echo "  Dock icon size:" "$(defaults read com.apple.dock tilesize 2>/dev/null || echo 'not set')"
      - echo "  Finder show hidden files:" "$(defaults read com.apple.finder AppleShowAllFiles 2>/dev/null || echo 'not set')"

  # Nix related commands
  update:
    desc: "Update all flake inputs"
    dir: '{{.NIX_DIR}}'
    cmds:
      - nix flake update

  update-input:
    desc: "Update specific flake input (usage: task nix:update-input INPUT=nixpkgs)"
    dir: '{{.NIX_DIR}}'
    cmds:
      - nix flake update "{{.INPUT}}"
    requires:
      vars: [INPUT]

  history:
    desc: "List all generations of the system profile"
    cmds:
      - nix profile history --profile /nix/var/nix/profiles/system

  repl:
    desc: "Open a nix repl with the flake"
    dir: '{{.NIX_DIR}}'
    cmds:
      - nix repl -f flake:nixpkgs

  clean:
    desc: "Remove system generations older than specified days (default: 7)"
    cmds:
      - echo "🧹 Cleaning old system generations (older than {{.CLEANUP_DAYS}} days)..."
      - sudo nix profile wipe-history --profile "{{.SYSTEM_PROFILE}}" --older-than "{{.CLEANUP_DAYS}}d"
      - echo "✅ System generations cleaned"

  clean-home:
    desc: "Clean home-manager generations"
    internal: true
    cmds:
      - echo "🧹 Cleaning home-manager generations..."
      - nix profile wipe-history --profile ~/.local/state/nix/profiles/home-manager --older-than "{{.CLEANUP_DAYS}}d" 2>/dev/null || echo "No home-manager profile found"

  gc:
    desc: "Garbage collect unused nix store entries"
    cmds:
      - echo "🗑️  Running garbage collection (older than {{.CLEANUP_DAYS}} days)..."
      # - sudo nix-collect-garbage --delete-older-than "{{.CLEANUP_DAYS}}d"
      - nix-collect-garbage --delete-older-than "{{.CLEANUP_DAYS}}d"
      - echo "✅ Garbage collection completed"

  optimize:
    desc: "Optimize nix store to save disk space"
    cmds:
      - echo "🔧 Optimizing Nix store..."
      - nix store optimise
      - echo "✅ Store optimization completed"

  disk-usage:
    desc: "Show disk usage information"
    cmds:
      - echo "💾 Disk Usage Information:"
      - echo "Nix store size:"
      - du -sh "{{.NIX_STORE_PATH}}" 2>/dev/null || echo "  Could not read nix store size"
      - echo "Home directory size:"
      - du -sh ~ 2>/dev/null || echo "  Could not read home directory size"

  maintenance:
    desc: "Run full maintenance (clean + gc + optimize)"
    deps: [disk-usage]
    cmds:
      - echo "🛠️  Running full maintenance..."
      - task: clean
      - task: clean-home
      - task: gc
      - task: optimize
      - task: disk-usage
      - echo "✅ Full maintenance completed"

  fmt:
    desc: "Format nix files in the repository"
    dir: '{{.NIX_DIR}}'
    cmds:
      - nix fmt

  gcroot:
    desc: "Show all auto gc roots in the nix store"
    cmds:
      - ls -al /nix/var/nix/gcroots/auto/

  # Utility tasks
  info:
    desc: "Show system information"
    cmds:
      - echo "System Information:"
      - echo "  Hostname:" "{{.HOSTNAME}}"
      - echo "  System:" "{{.SYSTEM}}"
      - echo "  Nix Dir:" "{{.NIX_DIR}}"
      - echo "  Current User:" "$(whoami)"
      - echo "  macOS Version:" "$(sw_vers -productVersion)"
      - echo "  Nix Version:" "$(nix --version 2>/dev/null || echo 'not found')"

  check-config:
    desc: "Check nix-darwin configuration syntax"
    dir: '{{.NIX_DIR}}'
    cmds:
      - echo "🔍 Checking configuration syntax..."
      - nix flake check
      - echo "✅ Configuration syntax is valid"

  lint:
    desc: "运行所有 Nix linting 工具"
    cmds:
      - echo "🔍 运行 Nix linting 工具..."
      - task: nix-lint:lint
      - echo "✅ Nix linting 完成"

#  status:
#    desc: "Show comprehensive system status"
#    silent: true
#    cmds:
#      - task: info
#      - task: disk-usage
#      - echo "Recent system generations:"
#      - nix profile history --profile "{{.SYSTEM_PROFILE}}" | head -10 || echo "  Could not read system profile history"
