apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - servicemonitor.yaml
  - prometheus-rules.yaml
  - grafana-dashboards.yaml

# 标签
commonLabels:
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/name: pag-monitoring

# 配置映射生成器
configMapGenerator:
  - name: grafana-datasources
    files:
      - datasources.yaml=grafana-datasources.yaml
    options:
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana-datasources

  - name: grafana-dashboard-providers
    files:
      - dashboard-providers.yaml=grafana-dashboard-providers.yaml
    options:
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana-providers

# 密钥生成器
secretGenerator:
  - name: grafana-admin-credentials
    literals:
      - admin-user=admin
      - admin-password=admin123
    options:
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana-auth

# 变换
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: "development"
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/component=monitoring"

# 图像策略
images:
  - name: grafana/grafana
    newTag: "10.4.0"
  - name: prom/prometheus
    newTag: "v2.45.0"
