apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: mysql
      interval: 30s
      path: /metrics
      scheme: http
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'mysql_.*'
          action: keep

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nightingale-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nightingale
    app.kubernetes.io/component: alerting
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nightingale
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      interval: 30s
      path: /api/n9e/metrics
      scheme: http

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: categraf-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: categraf
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: categraf
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
