rec {
  description = "NixOS for Me";

  inputs = {
    flake-parts.url = "github:hercules-ci/flake-parts";

    # Use existing nixpkgs inputs
    nixpkgs-darwin.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    # home-manager, used for managing user configuration
    home-manager = {
      url = "github:nix-community/home-manager/master";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    # nixos-generators for creating ISO images
    nixos-generators = {
      url = "github:nix-community/nixos-generators";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    darwin = {
      url = "github:lnl7/nix-darwin/master";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };
    determinate = {
      url = "https://flakehub.com/f/DeterminateSystems/determinate/*";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    # Keep nix-homebrew for compatibility
    # https://github.com/zhaofengli/nix-homebrew
    nix-homebrew.url = "github:zhaofengli-wip/nix-homebrew";

    nvf.url = "github:notashelf/nvf";

    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    # Stylix theming system
    stylix = {
      url = "github:nix-community/stylix";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    # https://github.com/nix-community/nixos-vscode-server
    vscode-server = {
      url = "github:nix-community/nixos-vscode-server";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # https://github.com/numtide/flake-utils
    utils.url = "github:numtide/flake-utils";
    nixos-hardware.url = "github:nixos/nixos-hardware";

    # https://github.com/nix-community/nix-index-database
    # Weekly prebuilt nix-index database.
    # what: 复用上游预生成索引，避免每台机器各自构建本地 database。预生成的 nix-index 数据库（定期更新），并带 NixOS/HM 模块与 wrapper。让 nix-locate / command-not-found 等不用本地跑索引也能快速查“哪个包提供某文件/命令”。
    # why: 对当前多平台仓库来说，这是低成本提升 nix-locate/command-not-found 体验的方式。
    # htu:
    nix-index-database = {
      url = "github:nix-community/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    agent-skills.url = "github:Kyure-A/agent-skills-nix";
    llm-agents.url = "github:numtide/llm-agents.nix";

    # nixos-cli - Modern NixOS management CLI
    # https://github.com/nix-community/nixos-cli
    nixos-cli = {
      url = "github:water-sucks/nixos";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # https://github.com/nix-community/nixos-facter
    # nixos-facter - Generate machine-readable hardware facts reports.
    # 注意：消费 report 的 NixOS modules 已经 upstream 到 nixpkgs，
    # 这里保留上游 flake 主要是为了拿到最新 CLI。
    # 是啥：NixOS 的“事实采集/硬件探测”方案：先生成机器 JSON 报告（facts），再由 NixOS 模块读取该报告做硬件相关的启用/参数决策。
    # 有啥用：批量装机/多硬件平台统一一份配置；减少手写硬件差异逻辑。
    # 怎么用：在目标机运行 facter 生成 report.json；在 NixOS 配置中引入模块并指向 report 文件路径，使配置随硬件事实自适配。
    # 决策：用在机器多且硬件差异大、想“一份配置跑全场”的场景；单机或少量固定硬件则直接 generate-config 就够。
    nixos-facter = {
      url = "github:nix-community/nixos-facter";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # deploy-rs - Multi-profile deployment tool
    # https://github.com/serokell/deploy-rs
    "deploy-rs" = {
      url = "github:serokell/deploy-rs";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nixos-wsl = {
      url = "github:nix-community/nixos-wsl/main";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # NixOS profile for Android Terminal / AVF
    nixos-avf = {
      url = "github:nix-community/nixos-avf";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # https://github.com/tak-bro/aicommit2
    # aicommit2.url = "github:tak-bro/aicommit2";

    # Declarative Dokploy stack for NixOS
    nix-dokploy.url = "github:el-kurto/nix-dokploy";
  };

  outputs = inputs @ {flake-parts, ...}:
    flake-parts.lib.mkFlake {inherit inputs;} {
      imports = [
        ({lib, ...}: {
          options.globals = lib.mkOption {
            description = "Cross-host shared configuration that is not host identity metadata.";
            type = lib.types.attrs;
          };

          config.globals = {
            workspace = {
              projectRoot = "/home/luck/Desktop/dotfiles";
              projectDir = "/home/luck/Desktop/dotfiles";
            };

            networking.nameservers = [
              "119.29.29.29"
              "223.5.5.5"
              "2400:3200::1"
              "2606:4700:4700::1111"
            ];

            # Global system preferences shared across hosts.
            # generated by `mkpasswd -m scrypt --rounds=11`
            auth = {
              initialHashedPassword = "$y$j9T$HD4YLOnwi/gUAthhKMSOB1$7mb6Ca8PC8uWxuNBT.APCk45CGuQhfIkXt9ZF3DYbP/";

              # Public keys trusted across the fleet.
              sshPublicKeys = [
                "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDth3yFJZ2p5tID2W2AHI3s6t6B8oU3nSVBIJANNxyIG nixos-cntr"
                "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF7x+rABbX8F5M7o3JhuzC3nifn3/ePgLXp5WaW/8FiE nixos-vps"
                "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFbnHbU+syywmhd+ywtJwsc8+IKuuph5Ol+TmxC8pZHH luck@macos-ws"
              ];
            };
          };
        })
        ./outputs
      ];
    };
}
