rec {
  description = "NixOS for Me";

  inputs = {
    flake-parts.url = "github:hercules-ci/flake-parts";

    # 主仓库默认收敛到 rolling branch。
    # Why:
    # - 大多数桌面/开发 host 继续跟随 nixpkgs-unstable，降低 branch maintenance 成本
    # - 公网 VPS 通过 host metadata 单独切到 stable package set，减少滚动更新风险
    # - channel 选择只在 host 边界发生，不引入全局双通道抽象层
    nixpkgs-darwin.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    nixpkgs-stable.url = "github:nixos/nixpkgs/nixos-26.05";

    # home-manager, used for managing user configuration
    home-manager = {
      # 默认随 rolling 演进；stable host 通过 useGlobalPkgs 复用对应系统 pkgs。
      url = "github:nix-community/home-manager/master";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    # nixos-generators for creating ISO images
    nixos-generators = {
      url = "github:nix-community/nixos-generators";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    darwin = {
      # nix-darwin 也统一跟随 rolling branch，避免 Darwin 侧单独维护 release pin。
      url = "github:lnl7/nix-darwin/master";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };
    determinate = {
      url = "https://flakehub.com/f/DeterminateSystems/determinate/*";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    # Keep nix-homebrew for compatibility
    nix-homebrew.url = "github:zhaofengli-wip/nix-homebrew";

    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    stylix = {
      url = "github:nix-community/stylix";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    nixos-hardware.url = "github:nixos/nixos-hardware";

    nix-index-database = {
      url = "github:nix-community/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    agent-skills.url = "github:Kyure-A/agent-skills-nix";
    llm-agents.url = "github:numtide/llm-agents.nix";
    mcp-servers-nix = {
      url = "github:natsukium/mcp-servers-nix";
      inputs.nixpkgs.follows = "nixpkgs-darwin";
    };

    # nixos-cli - Modern NixOS management CLI
    nixos-cli = {
      url = "github:water-sucks/nixos";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nixos-facter = {
      url = "github:nix-community/nixos-facter";
      # inputs.nixpkgs.follows = "nixpkgs";
    };

    "deploy-rs" = {
      url = "github:serokell/deploy-rs";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nixos-wsl = {
      url = "github:nix-community/nixos-wsl/main";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # NixOS profile for Android Terminal / AVF
    nixos-avf = {
      url = "github:nix-community/nixos-avf";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Nix unit testing tools
    nixt.url = "github:nix-community/nixt";
    nix-unit.url = "github:nix-community/nix-unit";
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [
        (
          { lib, ... }:
          {
            options.globals = lib.mkOption {
              description = "Cross-host shared configuration that is not host identity metadata.";
              type = lib.types.attrs;
            };

            config.globals = {
              workspace = {
                projectRoot = "/home/luck/Desktop/dotfiles";
                projectDir = "/home/luck/Desktop/dotfiles";
              };

              networking.nameservers = [
                "119.29.29.29"
                "223.5.5.5"
                "2400:3200::1"
                "2606:4700:4700::1111"
              ];

              # Global system preferences shared across hosts.
              # generated by `mkpasswd -m scrypt --rounds=11`
              auth = {
                initialHashedPassword = "$y$j9T$HD4YLOnwi/gUAthhKMSOB1$7mb6Ca8PC8uWxuNBT.APCk45CGuQhfIkXt9ZF3DYbP/";

                # Public keys trusted across the fleet.
                sshPublicKeys = [
                  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDth3yFJZ2p5tID2W2AHI3s6t6B8oU3nSVBIJANNxyIG nixos-cntr"
                  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF7x+rABbX8F5M7o3JhuzC3nifn3/ePgLXp5WaW/8FiE nixos-vps"
                  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFbnHbU+syywmhd+ywtJwsc8+IKuuph5Ol+TmxC8pZHH luck@macos-ws"
                ];
              };
            };
          }
        )
        ./outputs
      ];
    };
}
