---
# 用于处理一些通用（darwin和nixos都支持）且常用的task

version: '3'



includes:
  sk:
    taskfile: ./secrets/Taskfile.yml
    dir: ./secrets
  nixos: Taskfile.nixos.yml
  darwin: Taskfile.darwin.yml


# ssh -t luck@192.168.92.194 "sudo nix-store --delete $(readlink -f /nix/store/zc9s68h7rmbkm23ara98mjzwa2p1jdcl-source) --ignore-liveness"
# 遇到一个 nix/store cache问题，导致

tasks:
  rm-flake:
    desc: "用来移除指定flake包"
    cmds:
      - gum confirm "是否已经在flake.nix移除指定flake包了?"
      - nix flake lock
      - nix flake check
      - nix flake metadata


  why:
    desc: "定位失败 pkg：选择配置类型/Host + 失败 drv，然后跑 why-depends"
    vars:
      KIND:
        sh: 'd="$(nix eval --raw .#darwinConfigurations --apply "x: builtins.toString (builtins.length (builtins.attrNames x))" 2>/dev/null || echo 0)"; n="$(nix eval --raw .#nixosConfigurations --apply "x: builtins.toString (builtins.length (builtins.attrNames x))" 2>/dev/null || echo 0)"; { [ "$d" != "0" ] && echo darwin; [ "$n" != "0" ] && echo nixos; } | gum choose --header "选择配置类型"'
      HOST:
        sh: 'nix eval --raw ".#{{.KIND}}Configurations" --apply "x: builtins.concatStringsSep \"\\n\" (builtins.attrNames x)" | gum choose --header "选择 Host"'
      FAILED_DRV:
        sh: 'gum input --prompt "失败 .drv 路径: "'
      SYSTEM_DRV:
        sh: 'test "{{.KIND}}" = "darwin" && nix eval --raw ".#darwinConfigurations.{{.HOST}}.system.drvPath" || nix eval --raw ".#nixosConfigurations.{{.HOST}}.config.system.build.toplevel.drvPath"'
    cmds:
      - 'gum style --bold "SYSTEM_DRV: {{.SYSTEM_DRV}}"'
      - 'gum style --bold "FAILED_DRV: {{.FAILED_DRV}}"'
      - 'nix why-depends --all --derivation "{{.SYSTEM_DRV}}" "{{.FAILED_DRV}}" 2>&1 | gum pager'
      - 'gum confirm "看 nix log？" && nix log "{{.FAILED_DRV}}" 2>&1 | gum pager || true'



# 1. nix run nixpkgs#<pkg>, nix shell -p <pkg>, nix profile <pkg> 之间的区别？ 前两者都是临时安装，但是run不进入shell，并且通常用于执行flake。而shell则更多用于已有nix pkgs了，用来直接安装，并进入shell。而 profile则完全不推荐使用（并非nix的规范使用，profile是 nix-env -i 的继任者）。
# 2. 后两者有啥区别？shell 不也是会在 $HOME/.config 里生成配置吗？ 二者区别在于，shell相当于把pkg临时加入PATH，退出shell，PATH就恢复原样了。而profile则永远加进去了，就“污染”了环境。
# nix shell -p <pkg>
