---

version: '3'

includes:
  nix:
    taskfile: ./nix/Taskfile.yml
    dir: ./nix
  dev: ./devenv/Taskfile.yml



tasks:
  dotbot:
    desc: 修改dotbot配置之后，执行同步
    cmd: dotbot -c install.conf.yaml
    dir: '{{.USER_WORKING_DIR}}'
