version: '3'

includes:
  sk:
    taskfile: ./secrets/Taskfile.yml
    dir: ./secrets
  nixos: Taskfile.nixos.yml
  darwin: Taskfile.darwin.yml


# ssh -t luck@192.168.92.194 "sudo nix-store --delete $(readlink -f /nix/store/zc9s68h7rmbkm23ara98mjzwa2p1jdcl-source) --ignore-liveness"
# 遇到一个 nix/store cache问题，导致

tasks:
  rm-flake:
    desc: "用来移除指定flake包"
    cmds:
      - gum confirm "是否已经在flake.nix移除指定flake包了?"
      - nix flake lock
      - nix flake check
      - nix flake metadata
