---

services:
  metapi:
    image: 1467078763/metapi:latest
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./data:/app/data
    environment:
      AUTH_TOKEN: ${LLM_MetAPI}
      PROXY_TOKEN: ${LLM_MetAPI}
      CHECKIN_CRON: "0 8 * * *"
      BALANCE_REFRESH_CRON: "0 * * * *"
      PORT: ${PORT:-4000}
      DATA_DIR: /app/data
      TZ: ${TZ:-Asia/Shanghai}
    restart: unless-stopped
