name: caddy

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
    networks:
      - edge
    command:
      - caddy
      - run
      - --config
      - /etc/caddy/Caddyfile
      - --adapter
      - caddyfile
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

networks:
  edge:
    name: edge
    external: true
