[[instances]]
urls = [
    "http://nightingale:17000/metrics"
]

# Blackbox Exporter - 黑盒监控
[[instances]]
urls = [
    "http://blackbox_exporter:9115/metrics"
]

# Redis Exporter - Redis监控
[[instances]]
urls = [
    "http://redis_exporter:9121/metrics"
]

# SSL Exporter - TLS证书监控
[[instances]]
urls = [
    "http://ssl_exporter:9219/metrics"
]

# Cprobe - 整合的监控代理
[[instances]]
urls = [
    "http://cprobe:8080/metrics"
]
