apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-monitoring-config
  labels:
    component: monitoring
    environment: dev
    app.kubernetes.io/part-of: pag
data:
  prometheus.yml: |
    # Development Prometheus Configuration
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "dev_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'mysql-exporter'
        static_configs:
          - targets: ['mysql-exporter:9104']

      - job_name: 'application-metrics'
        static_configs:
          - targets: ['application:8080']
        metrics_path: '/metrics'
        scrape_interval: 15s

      - job_name: 'nightingale'
        static_configs:
          - targets: ['nightingale:8000']
        metrics_path: '/api/n9e/metrics'
        scrape_interval: 30s

      - job_name: 'categraf'
        static_configs:
          - targets: ['categraf:9100']
        scrape_interval: 30s

  alertmanager.yml: |
    # Development Alertmanager Configuration
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
        - match:
            severity: critical
          receiver: 'critical-alerts'
          continue: true
        - match:
            severity: warning
          receiver: 'warning-alerts'

    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://localhost:5001/'

      - name: 'critical-alerts'
        webhook_configs:
          - url: 'http://localhost:5001/critical'
        email_configs:
          - to: 'dev-alerts@example.com'
            subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
            body: |
              {{ range .Alerts }}
              Alert: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              Labels: {{ .Labels }}
              {{ end }}

      - name: 'warning-alerts'
        webhook_configs:
          - url: 'http://localhost:5001/warning'
        email_configs:
          - to: 'dev-warnings@example.com'
            subject: '[WARNING] {{ .GroupLabels.alertname }}'
            body: |
              {{ range .Alerts }}
              Alert: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              Labels: {{ .Labels }}
              {{ end }}

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']

  dev_rules.yml: |
    # Development Alert Rules
    groups:
      - name: dev.rules
        interval: 30s
        rules:
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High error rate detected"
              description: "Error rate is {{ $value }} errors per second"

          - alert: ServiceUnavailable
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Service is unavailable"
              description: "Service {{ $labels.instance }} is down"
