apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev-application-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/component: monitoring
    environment: dev
    app.kubernetes.io/part-of: pag
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: application
      environment: dev
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      scheme: http
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'app_.*'
          action: keep
        - sourceLabels: [__name__]
          targetLabel: __name__
          replacement: 'dev_${1}'

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev-database-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/component: database
    environment: dev
    app.kubernetes.io/part-of: pag
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      environment: dev
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'mysql_.*'
          action: keep

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev-custom-metrics-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/component: custom-metrics
    environment: dev
    app.kubernetes.io/part-of: pag
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: custom-metrics
      environment: dev
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      interval: 30s
      path: /custom-metrics
      scheme: http
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'custom_.*'
          action: keep
