[[instances]]
urls = [
    "http://nightingale:17000/metrics"
]

# Blackbox Exporter - 黑盒监控
[[instances]]
urls = [
    "http://devenv_blackbox_exporter:9115/metrics"
]

# Redis Exporter - Redis 监控
[[instances]]
urls = [
    "http://devenv_redis_exporter:9121/metrics"
]

# SSL Exporter - TLS证书监控
[[instances]]
urls = [
    "http://devenv_ssl_exporter:9219/metrics"
]
