{lib}: let
  username = "luck";
  projectRoot = "/home/${username}/Desktop/dotfiles";
in {
  # FIXME 移除掉所有 myvars. 正确的做法是所有的 username, mail 这些都应该配置到host里（类似 nixos-unified 这种）。
  ## 1、最多的就是 username = "luck"; 有37处
  ## 2、SSHPubKeys 7次
  ## 3、initialHashedPassword 有 2次
  ## 4、原先的 colmenaTargets 已移除，目标主机改由各 role 节点文件内声明
  ## 5、myvars.mail 有 3次
  ## projectRoot 也被 nixos-cli 之类的被调用，也确实有用。

  inherit username projectRoot;
  # TODO: remove once all modules use projectRoot directly
  projectDir = projectRoot;

  userfullname = "lucas";
  mail = "yyzw@live.com";

  timeZone = "Asia/Shanghai";

  networking = import ./networking.nix {inherit lib;};

  # Global system preferences (used by all hosts)
  # These can be overridden by host-specific settings above
  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  # mkpasswd -m yescrypt --rounds=５ <>
  initialHashedPassword = "$y$j9T$HD4YLOnwi/gUAthhKMSOB1$7mb6Ca8PC8uWxuNBT.APCk45CGuQhfIkXt9ZF3DYbP/";

  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  SSHPubKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDth3yFJZ2p5tID2W2AHI3s6t6B8oU3nSVBIJANNxyIG nixos-cntr"

    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF7x+rABbX8F5M7o3JhuzC3nifn3/ePgLXp5WaW/8FiE nixos-vps"

    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFbnHbU+syywmhd+ywtJwsc8+IKuuph5Ol+TmxC8pZHH luck@macos-ws"
  ];
}
