{lib}: {
  username = "luck";
  userfullname = "lucas";
  mail = "yyzw@live.com";

  networking = import ./networking.nix {inherit lib;};

  # Host-specific configurations
  # Following RNC pattern: hosts are identified by hostname and variables are looked up dynamically
  hosts = {
    nixos-ws = {
      # Hardware configuration
      gpuType = "nvidia";
      hostId = "5ab03f50";

      # Hardware IDs for hybrid GPU setups (Intel/NVIDIA Prime or AMD/NVIDIA)
      intelID = "PCI:1:0:0";
      amdgpuID = "PCI:5:0:0";
      nvidiaID = "PCI:0:2:0";

      # Display Manager
      displayManager = "sddm";

      # System preferences
      browser = "floorp";
      terminal = "wezterm";
      keyboardLayout = "us";
      consoleKeyMap = "us";
      clock24h = true;

      # Hyprland Settings
      extraMonitorSettings = "";

      # Flatpak configuration
      flatpakEnable = true;

      # Development tools
      dockerEnable = true;
      virtManagerEnable = false;

      # Media and graphics
      blenderEnable = false;
      kritaEnable = false;
    };

    # Template for future hosts - uncomment and customize as needed
    # future-host = {
    #   gpuType = "amd";
    #   hostId = "abcdef";
    #   keyboardLayout = "us";
    #   # ... other host-specific settings
    # };
  };

  # Global system preferences (used by all hosts)
  # These can be overridden by host-specific settings above
  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  # Password: 159357
  initialHashedPassword = "$7$GU..../....B30bx1bkdH7w1QUzj.jnw1$gMoazOuSKu41B5C/jSEyN6Pv6Wl74GEM3J6D1gnsu0A";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  mainSshAuthorizedKeys = [
    # The main ssh keys for daily usage
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIKlN+Q/GxvwxDX/OAjJHaNFEznEN4Tw4E4TwqQu/eD6 ryan@idols-ai"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwoI5MAogEa726jwwHL5EgM1X/i2A5d2pgV7i7t8fzB ryan@shoukei"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDc1PNTXzzvd93E+e9LXvnEzqgUI5gMTEF/IitvzgmL+ ryan@frieren"
  ];
  secondaryAuthorizedKeys = [
    # the backup ssh keys for disaster recovery
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMzYT0Fpcp681eHY5FJV2G8Mve53iX3hMOLGbVvfL+TF ryan@romantic"
  ];
}
