---
# taskfile-lint.yml
# 用于静态检查 Taskfile.yml 的 lint 配置文件，专注 Taskfile 特有语法
# 移除难以实现的规则（如硬编码检测、危险命令、模板复用、变更注释）
# 保留 cmds 行数限制规则

version: "1.0"

rules:
  document-structure:
    required-fields:
      - version: {required: true, description: "必须包含 Taskfile 版本号 (version)"}
      - tasks: {required: true, description: "必须包含 tasks 节点"}
    error-level: error  # 缺少必要字段视为严重错误

  # 变量管理规则
  vars:
    forbidden-keys:
      - pattern: "(password|secret|key|token|credential)"
        description: "禁止在 vars 中使用敏感关键词（如 password, secret, key, token, credential）"
        error-level: error
    unique-keys:
      enforce: true
      description: "vars 中的键必须唯一"
      error-level: error

  # 环境变量管理规则
  env:
    sensitive-data:
      enforce: true
      description: "敏感数据（如 API_KEY, DEPLOY_KEY）必须定义在 env 而非 vars"
      regex-check: "(API_KEY|DEPLOY_KEY|DB_CRED|PASSWORD|TOKEN)"
      error-level: error
    file-based:
      enforce: true
      description: "敏感 env 变量应引用文件（如 ./secrets/api_key），禁止直接内联值"
      regex-check: "^[^./]"  # 检测非文件路径的内联值
      error-level: error

  # 任务体系规则
  tasks:
    standard-tasks:
      allowed:
        - init
        - build
        - test
        - run
        - deploy
        - lint
        - clean
      description: "所有任务必须归类到标准任务体系 (init|build|test|run|deploy|lint|clean)"
      error-level: error
    required-attributes: # TODO 这里有问题。
      - desc:
          required: true
          description: "每个任务必须包含 desc 属性，提供明确描述"
          error-level: error
      - silent:
          required: true
          description: "每个任务必须显式声明 silent 属性 (true/false)"
          error-level: error
      - interactive:
          required: false
          description: "危险操作（如 db-reset, clean, deploy）必须设置 interactive: true"
          applies-to: ["db-reset", "clean", "deploy"]
          error-level: error
      - internal:
          required: false
          description: "被其他任务调用的子任务必须设置 internal: true"
          error-level: warning
    command-lines:
      max: 3
      description: "每个任务的 cmds 列表不得超过 3 条 shell 命令，以保持简洁性和可读性"
      error-level: warning

  # 模板复用规则
  templates:
    unique-names:
      enforce: true
      description: "templates 中的锚点名称必须唯一"
      error-level: error

# 忽略规则
ignore:
  paths:
    - "examples/**"  # 忽略示例目录
    - "archive/**"   # 忽略归档目录
  tasks:
    - "legacy-*"     # 忽略以 legacy- 开头的任务（用于兼容旧任务）

# 输出格式
output:
  format: standard  # 可选：standard, json, github-actions
  verbosity: detailed  # 可选：minimal, detailed
  show-line-numbers: true
