---
version: '3'

vars:
  EXTENSION_NAME: xts
  BUILD_DIR: dist
  VICINAE_EXTENSIONS_DIR: ~/.config/vicinae/extensions

tasks:
  install:
    desc: "Install dependencies"
    cmds:
      - pnpm install

  dev:
    desc: "Run extension in development mode"
    cmds:
      - pnpm dev

  build:
    desc: "vici build本身就会build，并把打包好的js放到$HOME/.local/share/viciane/extensions这个目标path"
    cmds:
      - pnpm build
