# Homebrew to Nix package mapping
# This file maps brew formulae and casks to their Nix equivalents

{
  # Command line tools (formulae)
  formulae = {
    "ack" = "ack";
    "ansible" = "ansible";
    "ansible-lint" = "ansible-lint";
    "apr-util" = "apr-util";
    "autocorrect" = "autocorrect";
    "automake" = "automake";
    "bat" = "bat";
    "bfg" = "bfg-repo-cleaner";
    "binutils" = "binutils";
    "cabextract" = "cabextract";
    "cariddi" = null; # Not available in nixpkgs
    "carthage" = "carthage";
    "chsrc" = null; # Not available in nixpkgs
    "clang-format" = "clang-tools";
    "cloc" = "cloc";
    "cloudflare-wrangler" = "wrangler";
    "cmake" = "cmake";
    "colima" = "colima";
    "direnv" = "direnv";
    "docker" = "docker";
    "docker-compose" = "docker-compose";
    "docker-credential-helper" = "docker-credential-helpers";
    "dotbot" = "dotbot";
    "eslint" = "nodePackages.eslint";
    "etolbakov/taps/excalidocker" = null; # Custom tap, not available
    "excalidraw-converter" = null; # Not available in nixpkgs
    "fastfetch" = "fastfetch";
    "fcrackzip" = "fcrackzip";
    "fetch" = null; # Ambiguous name
    "ffmpeg" = "ffmpeg";
    "fish" = "fish";
    "fping" = "fping";
    "gcc" = "gcc";
    "gcc@9" = null; # Specific version, use gcc
    "gh" = "gh";
    "git" = "git";
    "git-lfs" = "git-lfs";
    "git-quick-stats" = "git-quick-stats";
    "git-who" = null; # Not available in nixpkgs
    "gitleaks" = "gitleaks";
    "gitlint" = "gitlint";
    "go-task" = "go-task";
    "gobject-introspection" = "gobject-introspection";
    "goctl" = null; # Not available in nixpkgs
    "gofumpt" = "gofumpt";
    "golangci-lint" = "golangci-lint";
    "goreleaser" = "goreleaser";
    "graphviz" = "graphviz";
    "grpcurl" = "grpcurl";
    "hadolint" = "hadolint";
    "helmfile" = "helmfile";
    "htop" = "htop";
    "httpie" = "httpie";
    "imagemagick" = "imagemagick";
    "inetutils" = "inetutils";
    "iproute2mac" = null; # macOS specific, not needed in nix
    "jq" = "jq";
    "jump" = "jump";
    "kompose" = "kompose";
    "kube-linter" = "kube-linter";
    "kubectx" = "kubectx";
    "libimobiledevice" = "libimobiledevice";
    "libpcap" = "libpcap";
    "lux" = "lux";
    "lychee" = "lychee";
    "mac-cleanup/mac-cleanup-py/mac-cleanup-py" = null; # Custom tap
    "markdownlint-cli" = "markdownlint-cli";
    "mdt" = null; # Not available in nixpkgs
    "minikube" = "minikube";
    "mockery" = "mockery";
    "mosh" = "mosh";
    "mplayer" = "mplayer";
    "mysql-client@8.0" = "mysql80";
    "nasm" = "nasm";
    "ncdu" = "ncdu";
    "nmap" = "nmap";
    "optipng" = "optipng";
    "p7zip" = "p7zip";
    "pandoc" = "pandoc";
    "pgloader" = "pgloader";
    "pipx" = "pipx";
    "pngquant" = "pngquant";
    "pnpm" = "nodePackages.pnpm";
    "pre-commit" = "pre-commit";
    "protoc-gen-go" = "protoc-gen-go";
    "protoc-gen-go-grpc" = "protoc-gen-go-grpc";
    "pygments" = "python3Packages.pygments";
    "rclone" = "rclone";
    "rustup" = "rustup";
    "shellcheck" = "shellcheck";
    "speedtest-cli" = "speedtest-cli";
    "sshpass" = "sshpass";
    "subfinder" = "subfinder";
    "talisman" = "talisman";
    "the_silver_searcher" = "silver-searcher";
    "tree" = "tree";
    "trufflehog" = "trufflehog";
    "trzsz-go" = null; # Not available in nixpkgs
    "ugit" = null; # Not available in nixpkgs
    "urlscan" = "urlscan";
    "uv" = "uv";
    "vegeta" = "vegeta";
    "viddy" = "viddy";
    "wget" = "wget";
    "yamllint" = "yamllint";
    "yarn" = "yarn";
    "yq" = "yq";
  };

  # GUI applications (casks)
  casks = {
    "alfred" = null; # Keep using homebrew for GUI apps
    "android-platform-tools" = "android-tools";
    "goland" = null; # Keep using homebrew for GUI apps
    "google-chrome" = null; # Keep using homebrew for GUI apps
    "hammerspoon" = null; # Keep using homebrew for GUI apps
    "hyperconnect" = null; # Keep using homebrew for GUI apps
    "mihomo-party" = null; # Keep using homebrew for GUI apps
    "tencent-lemon" = null; # Keep using homebrew for GUI apps
    "wechat" = null; # Keep using homebrew for GUI apps
  };
}
