# Development Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "dev_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'application-metrics'
    static_configs:
      - targets: ['application:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'nightingale'
    static_configs:
      - targets: ['nightingale:8000']
    metrics_path: '/api/n9e/metrics'
    scrape_interval: 30s

  - job_name: 'categraf'
    static_configs:
      - targets: ['categraf:9100']
    scrape_interval: 30s
