#!/usr/bin/env nu
# zzz.nu — /zzz skill router
# Usage: nu <skill_dir> <subcommand>
# Behavior:
#   1. Read aliases.json from references/ (generated by gen-aliases.nu)
#   2. Look up subcommand → filename
#   3. If found, log a hit and print references/<filename>.md
#   4. If not found, print ERROR + available subcommands

def get-aliases [skill_dir: string] {
    open ($skill_dir | path join "aliases.json")
}

def get-available [aliases: record] {
    $aliases | columns | sort | str join ' '
}

def log-hit [sub: string, file: string] {
    let stats_file = $"($env.HOME)/.claude/zzz-stats.jsonl"
    let entry = ({
        sub: $sub
        target: $file
        ts: (date now | format date "%Y-%m-%dT%H:%M:%S%z")
    } | to json)
    try { $entry | save --append $stats_file } catch {|e|}
}

def resolve-file [aliases: record, sub: string] {
    $aliases | get --optional $sub
}

def main [skill_dir: string, subcommand: string] {
    let sub = ($subcommand | str trim | str lowercase)
    let ref_dir = ($skill_dir | path join "references")
    let aliases = (get-aliases $skill_dir)
    let file = (resolve-file $aliases $sub)

    if $file != null {
        let target = ($ref_dir | path join $"($file).md")
        if ($target | path exists) {
            log-hit $sub $file
            print $"references/($file).md"
            return
        }
    }

    let available = (get-available $aliases)
    print $"ERROR: unknown subcommand: ($sub)"
    print $"Available: ($available)"
}
