#!/usr/bin/env nu
# zzz.nu — /zzz skill router
# Usage: nu <skill_dir> <subcommand>
# Behavior:
#   1. Read aliases.json from references/ (generated by gen-aliases.nu)
#   2. Look up subcommand → filename
#   3. If found, log a hit and print references/<filename>.md
#   4. If not found, print ERROR + available subcommands

def get-aliases [skill_dir: string] {
    open ($skill_dir | path join "aliases.json")
}

def get-available [aliases: record] {
    $aliases | columns | sort | str join ' '
}

def log-hit [sub: string, file: string] {
    # Counter file (not jsonl): upsert count per subcommand.
    # Fresh start: do not read ~/.claude/zzz-stats.jsonl if present.
    let stats_file = $"($env.HOME)/.claude/zzz-stats.json"
    let ts = (date now | format date "%Y-%m-%dT%H:%M:%S%z")
    try {
        let stats = (
            if ($stats_file | path exists) {
                open $stats_file
            } else {
                {}
            }
        )
        let prev = ($stats | get --optional $sub)
        let count = (
            if $prev == null {
                1
            } else {
                ($prev | get --optional count | default 0) + 1
            }
        )
        let entry = {
            count: $count
            last_ts: $ts
            target: $file
        }
        let updated = ($stats | upsert $sub $entry)
        $updated | to json | save --force $stats_file
    } catch {|e|}
}

def resolve-file [aliases: record, sub: string] {
    $aliases | get --optional $sub
}

def main [skill_dir: string, subcommand: string, topic?: string] {
    let sub = ($subcommand | str trim | str lowercase)
    let ref_dir = ($skill_dir | path join "references")
    let aliases = (get-aliases $skill_dir)
    let file = (resolve-file $aliases $sub)

    if $file != null {
        let target = ($ref_dir | path join $"($file).md")
        if ($target | path exists) {
            log-hit $sub $file
            print $"references/($file).md"

            # strike 特例：把 topic 传给 counter 脚本，返回当前 turn 状态
            if $sub == "strike" and $topic != null {
                let counter = ($skill_dir | path join "strike.nu")
                let state = (open $"($env.HOME)/.claude/strike-state.json" | default {active:false,topic:"",turn:0})
                # topic 变了 → 新 topic；没变（或未激活）→ submit 延续/激活
                if $state.active and $state.topic == $topic {
                    print (nu $counter submit $topic | str trim)
                } else {
                    print (nu $counter new $topic | str trim)
                }
            }
            return
        }
    }

    let available = (get-available $aliases)
    print $"ERROR: unknown subcommand: ($sub)"
    print $"Available: ($available)"
}
