apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-routes.yaml

# 标签
commonLabels:
  app.kubernetes.io/component: ingress
  app.kubernetes.io/name: pag-ingress

# 变换
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: "development"
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/component=ingress"
