# [Backend]
# 后端选择：auto（自动检测 Hyprland/Wayland）、hyprland、hyprsunset、wayland
# 推荐保持 auto，除非你明确只用 Hyprland
backend = "auto"
# 过渡模式：
#   geo         → 按地理位置自动计算日出日落（推荐）
#   finish_by   → 手动指定“结束于”某时间
#   start_at    → 手动指定“开始于”某时间
#   center      → 以固定时间为中心对称过渡
#   static      → 固定色温，不随时间变化
transition_mode = "geo"

# [Smoothing]
# 是否启用启动/退出时的平滑动画
smoothing = true
# 程序启动时淡入动画时长（秒），0 = 瞬间生效
startup_duration = 0.3
# 程序退出时淡出动画时长（秒），0 = 瞬间消失
shutdown_duration = 0.3
# 平滑过渡的基准更新间隔（ms），值越小越丝滑但 CPU 占用略增
# 1ms 过于激进，5~10 已足够流畅
adaptive_interval = 5

# [Time-based config]
# 夜间色温（K），值越低越黄。4500K 偏橙，5200~5500K 暖而不刺眼
night_temp = 5500
# 白天色温（K），6500K 为标准日光
day_temp = 6500
# 夜间 Gamma 百分比（10~100），值越低画面越暗
# 90% 会让夜间明显偏暗，建议 95~100
night_gamma = 98
# 白天 Gamma 百分比，保持 100
day_gamma = 100
# 日出/日落过渡期间的检查频率（秒）
# 60s 略显跳跃，30s 更细腻自然
update_interval = 30

# [Static config]
# static 模式下的固定色温（仅 transition_mode = static 时生效）
static_temp = 6500
# static 模式下的固定 Gamma
static_gamma = 100

# [Manual transitions]
# 手动模式下的日落时间（HH:MM:SS），仅非 geo 模式生效
# geo 模式下建议注释掉，避免误解
# sunset = "19:00:00"
# 手动模式下的日出时间
# sunrise = "06:00:00"
# 手动模式下从日温到夜温的过渡时长（分钟）
# geo 模式仍会参考此值用于平滑插值，建议 20~30
transition_duration = 30

# [Geolocation]
# 地理纬度（北纬正，南纬负），首次运行可自动获取
# 保留 4 位小数即可，过多数值无意义
latitude = 31.2222
# 地理经度（东经正，西经负）
longitude = 121.4590
