---
version: "3"

includes:
  # devops
  git: taskfile/devops/Taskfile.git.yml
  linters: taskfile/devops/Taskfile.linters.yml
  ansible: taskfile/devops/Taskfile.ansible.yml
  gor: taskfile/devops/Taskfile.goreleaser.yml
  caddy: taskfile/devops/Taskfile.caddy.yml
  pc: taskfile/devops/Taskfile.pre-commit.yml
  rclone: taskfile/devops/Taskfile.rclone.yml
  tf: taskfile/devops/Taskfile.tf.yml

  # go
  gz: taskfile/go/Taskfile.gz.yml
  go: taskfile/go/Taskfile.go.yml

  # k8s
  k3d: taskfile/k8s/Taskfile.k3d.yml
  docker: taskfile/k8s/Taskfile.docker.yml
  mk: taskfile/k8s/Taskfile.minikube.yml
  dc: taskfile/k8s/Taskfile.dc.yml
  helm: taskfile/k8s/Taskfile.helm.yml
  k8s: taskfile/k8s/Taskfile.k8s.yml

  # kernel
  linux: taskfile/kernel/Taskfile.linux.yml
  monitor: taskfile/kernel/Taskfile.monitor.yml
  pkg: taskfile/kernel/Taskfile.pkg.yml
  net: taskfile/kernel/Taskfile.z.yml
  shell: taskfile/kernel/Taskfile.shell.yml
  ssh: taskfile/kernel/Taskfile.ssh.yml
  tcpdump: taskfile/kernel/Taskfile.tcpdump.yml
  sysd: taskfile/kernel/Taskfile.systemd.yml

  # mac
  mac: taskfile/mac/Taskfile.mac.yml
  mac-cleanup: taskfile/mac/Taskfile.mac-cleanup.yml
  brew: taskfile/mac/Taskfile.brew.yml
  img: taskfile/mac/Taskfile.img.yml
  trzsz: taskfile/mac/Taskfile.trzsz.yml
  scrapy: taskfile/mac/Taskfile.scrapy.yml
  me: taskfile/mac/Taskfile.me.yml
  alfred: taskfile/mac/Taskfile.alfred.yml
  pnpm: taskfile/mac/Taskfile.pnpm.yml
  ruler: taskfile/mac/Taskfile.ruler.yml
  singbox: taskfile/mac/Taskfile.singbox.yml
  sc: taskfile/mac/Taskfile.scratches.yml

  # network
  netw: taskfile/network/Taskfile.network.yml
  gost: taskfile/network/Taskfile.gost.yml
  ss: taskfile/network/Taskfile.ss.yml
  tcp: taskfile/network/Taskfile.TCP.yml
  throughput: taskfile/network/Taskfile.throughput.yml
  dig: taskfile/network/Taskfile.dig.yml
  whois: taskfile/network/Taskfile.whois.yml
  ping: taskfile/network/Taskfile.ping.yml
  tracepath: taskfile/network/Taskfile.tracepath.yml
  traceroute: taskfile/network/Taskfile.traceroute.yml
  nstat: taskfile/network/Taskfile.nstat.yml
  nc: taskfile/network/Taskfile.ICMP.yml
  nz: taskfile/network/Taskfile.z.yml


  # nix
  deploy: taskfile/nix/Taskfile.deploy.yml
  flake: taskfile/nix/Taskfile.flake.yml
  store: taskfile/nix/Taskfile.store.yml
  test: taskfile/nix/Taskfile.test.yml
  sops: taskfile/nix/Taskfile.sops.yml

  # works
  sec: taskfile/works/Taskfile.sec.yml




tasks:
  default:
    silent: true
    interactive: true
    cmd: task -l
