---
version: "3"

includes:
  # devops
  git: devops/Taskfile.git.yml
  linters: devops/Taskfile.linters.yml
  ansible: devops/Taskfile.ansible.yml
  gor: devops/Taskfile.goreleaser.yml
  caddy: devops/Taskfile.caddy.yml
  pc: devops/Taskfile.pre-commit.yml
  rclone: devops/Taskfile.rclone.yml
  tf: devops/Taskfile.tf.yml

  # go
  gz: go/Taskfile.gz.yml
  go: go/Taskfile.go.yml

  # k8s
  k3d: k8s/Taskfile.k3d.yml
  docker: k8s/Taskfile.docker.yml
  mk: k8s/Taskfile.minikube.yml
  dc: k8s/Taskfile.dc.yml
  helm: k8s/Taskfile.helm.yml
  k8s: k8s/Taskfile.k8s.yml

  # kernel
  linux: kernel/Taskfile.linux.yml
  monitor: kernel/Taskfile.monitor.yml
  pkg: kernel/Taskfile.pkg.yml
  shell: kernel/Taskfile.shell.yml
  sysd: kernel/Taskfile.systemd.yml
  power: kernel/Taskfile.power.yml
  proc: kernel/proc/default.yml

  # mac
  mac: mac/Taskfile.mac.yml
  mac-cleanup: mac/Taskfile.mac-cleanup.yml
  brew: mac/Taskfile.brew.yml
  img: mac/Taskfile.img.yml
  trzsz: mac/Taskfile.trzsz.yml
  # scrapy: mac/Taskfile.scrapy.yml
  me: mac/Taskfile.me.yml
  # alfred: mac/Taskfile.alfred.yml
  pnpm: mac/Taskfile.pnpm.yml
  # ruler: mac/Taskfile.ruler.yml
  sc: mac/Taskfile.scratches.yml

  # network
  gost: network/proxy/Taskfile.gost.yml
  ss: network/tcp/Taskfile.ss.yml
  tcp: network/tcp/Taskfile.TCP.yml
  throughput: network/perf/Taskfile.iperf.yml
  dig: network/dns/Taskfile.dig.yml
  whois: network/dns/Taskfile.whois.yml
  ping: network/ip/icmp/Taskfile.ping.yml
  tracepath: network/ip/icmp/Taskfile.tracepath.yml
  traceroute: network/ip/icmp/Taskfile.traceroute.yml
  nstat: network/ip/icmp/Taskfile.nstat.yml
  nc: network/ip/icmp/Taskfile.ICMP.yml
  nz: network/Taskfile.z.yml
  ip: network/ip/Taskfile.iproute2.yml
  mtr: network/ip/icmp/Taskfile.mtr.yml
  fping: network/ip/icmp/Taskfile.fping.yml
  hping: network/ip/icmp/Taskfile.hping3.yml
  nping: network/ip/icmp/Taskfile.nping.yml
  nft: network/firewall/Taskfile.nft.yml
  ipt: network/firewall/Taskfile.iptables.yml
  conntrack: network/firewall/Taskfile.conntrack.yml
  ethtool: network/ip/Taskfile.ethtool.yml
  tc: network/ip/Taskfile.tc.yml
  bpftool: network/ip/Taskfile.bpftool.yml
  bpftrace: network/ip/Taskfile.bpftrace.yml
  netperf: network/perf/Taskfile.netperf.yml
  trafgen: network/perf/Taskfile.trafgen.yml
  pktgen: network/perf/Taskfile.pktgen.yml
  nmap: network/scan/Taskfile.nmap.yml
  naabu: network/scan/Taskfile.naabu.yml
  arping: network/l2/Taskfile.arping.yml
  bridge: network/l2/Taskfile.bridge.yml
  lldp: network/l2/Taskfile.lldp.yml
  wifi: network/l2/Taskfile.iw.yml
  macchanger: network/l2/Taskfile.macchanger.yml
  curl: network/http/Taskfile.curl.yml
  http: network/http/Taskfile.httpie.yml
  wget: network/http/Taskfile.wget.yml
  openssl: network/tls/Taskfile.openssl.yml
  grpcurl: network/grpc/Taskfile.grpcurl.yml
  websocat: network/ws/Taskfile.websocat.yml
  chrony: network/Taskfile.chrony.yml
  nat: network/nat/Taskfile.nat.yml


  # nix
  deploy: nix/Taskfile.deploy.yml
  flake: nix/Taskfile.flake.yml
  store: nix/Taskfile.store.yml
  test: nix/Taskfile.test.yml
  sops: nix/Taskfile.sops.yml

  # works
  sec: works/Taskfile.sec.yml
  skills: works/AI/Taskfile.skills.yml




tasks:
  default:
    desc: "default 任务"
    summary: "task -g default"
    silent: true
    interactive: true
    cmd: task -l
