---
version: "3"

includes:
  # devops
  # linters: devops/Taskfile.linters.yml
  # ansible: devops/Taskfile.ansible.yml
  # gor: devops/Taskfile.goreleaser.yml
  # caddy: devops/Taskfile.caddy.yml
  devops:
    taskfile: devops/Taskfile.yml
    flatten: true

  # langs
  langs:
    taskfile: langs/Taskfile.yml
    flatten: true

  # k8s
  k8s:
    taskfile: k8s/Taskfile.yml
    flatten: true

  # kernel
  kernel:
    taskfile: kernel/Taskfile.yml
    flatten: true

  # mac
  macos:
    taskfile: mac/Taskfile.yml
    flatten: true

  # network
  network:
    taskfile: network/Taskfile.yml
    flatten: true

  # nix
  # 注意这部分同时在 global task 和 dotfiles项目级taskfile里引用（为了同时方便全局调用和在项目里调用）
  nix:
    taskfile: nix/Taskfile.yml

  # works
  works:
    taskfile: works/Taskfile.yml
    flatten: true




tasks:
  default:
    desc: "default 任务"
    summary: "task -g default"
    silent: true
    interactive: true
    cmd: task --list

  count:
    desc: "task count (注意只有 public task)"
    cmd: task --list --json | jq '.tasks | length'
