---
version: "3"

includes:
  # devops
  git: devops/Taskfile.git.yml
  linters: devops/Taskfile.linters.yml
  ansible: devops/Taskfile.ansible.yml
  gor: devops/Taskfile.goreleaser.yml
  caddy: devops/Taskfile.caddy.yml
  pc: devops/Taskfile.pre-commit.yml
  rclone: devops/Taskfile.rclone.yml
  droid: devops/Taskfile.droid.yml

  # go
  gz: go/Taskfile.gz.yml
  go: go/Taskfile.go.yml

  # k8s
  k3d: k8s/Taskfile.k3d.yml
  docker: k8s/Taskfile.docker.yml
  mk: k8s/Taskfile.minikube.yml
  dc: k8s/Taskfile.dc.yml
  helm: k8s/Taskfile.helm.yml
  k8s: k8s/Taskfile.k8s.yml

  # kernel
  linux: kernel/Taskfile.linux.yml
  monitor: kernel/Taskfile.monitor.yml
  pkg: kernel/Taskfile.pkg.yml
  shell: kernel/Taskfile.shell.yml
  sysd: kernel/Taskfile.systemd.yml
  power: kernel/Taskfile.power.yml
  proc: kernel/proc/default.yml

  # mac
  mac: mac/Taskfile.mac.yml
  mac-cleanup: mac/Taskfile.mac-cleanup.yml
  brew: mac/Taskfile.brew.yml
  img: mac/Taskfile.img.yml
  trzsz: mac/Taskfile.trzsz.yml
  # scrapy: mac/Taskfile.scrapy.yml
  me: mac/Taskfile.me.yml
  # alfred: mac/Taskfile.alfred.yml
  pnpm: mac/Taskfile.pnpm.yml
  # ruler: mac/Taskfile.ruler.yml
  sc: mac/Taskfile.scratches.yml

  # network
  gost: network/Taskfile.gost.yml
  ss: network/Taskfile.ss.yml
  tcp: network/Taskfile.TCP.yml
  throughput: network/Taskfile.iperf.yml
  dns: network/Taskfile.DNS.yml
  ping: network/Taskfile.ping.yml
  traceroute: network/Taskfile.traceroute.yml
  nz: network/Taskfile.z.yml
  ip: network/Taskfile.iproute2.yml
  nping: network/Taskfile.nping.yml
  firewall: network/Taskfile.firewall.yml
  ethtool: network/Taskfile.ethtool.yml
  bpftool: network/Taskfile.BPF.yml
  bpftrace: network/Taskfile.BPF.yml
  nmap: network/Taskfile.nmap.yml
  naabu: network/Taskfile.naabu.yml
  arping: network/Taskfile.arping.yml
  wifi: network/Taskfile.iw.yml
  curl: network/Taskfile.curl.yml
  openssl: network/Taskfile.openssl.yml
  grpcurl: network/Taskfile.grpcurl.yml
  ws: network/Taskfile.ws.yml
  chrony: network/Taskfile.chrony.yml


  # nix
  deploy: nix/Taskfile.deploy.yml
  flake: nix/Taskfile.flake.yml
  store: nix/Taskfile.store.yml
  test: nix/Taskfile.test.yml
  sops: nix/Taskfile.sops.yml

  # works
  sec: works/Taskfile.sec.yml
  skills: works/AI/Taskfile.skills.yml
  codex: works/AI/Taskfile.codex.yml




tasks:
  default:
    desc: "default 任务"
    summary: "task -g default"
    silent: true
    interactive: true
    cmd: task -l
