apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# 开发环境日志配置组件

# 配置映射生成器 - 日志配置
configMapGenerator:
  - name: dev-logging-config
    files:
      - logback-spring.xml=conf/logback-spring.xml
      - log4j2.xml=conf/log4j2.xml
    options:
      labels:
        component: logging
        environment: dev

# 变换 - 应用日志配置
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: "DEBUG"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_FORMAT
          value: "json"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_FILE
          value: "/var/log/application.log"
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/component in (monitoring, alerting, metrics)"

  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: log-volume
          emptyDir: {}
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: log-volume
          mountPath: /var/log
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/component in (monitoring, alerting, metrics)"

# 资源
resources:
  - logging-configmap.yaml
