# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  chrome-devtools-mcp = {
    pname = "chrome-devtools-mcp";
    version = "0.21.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/chrome-devtools-mcp/-/chrome-devtools-mcp-0.21.0.tgz";
      sha256 = "sha256-KMHWSSctf6ihIT792yZeTqaYuHqmUanN2SJje5PI184=";
    };
  };
  launchk = {
    pname = "launchk";
    version = "launchk-0.3.1";
    src = fetchFromGitHub {
      owner = "intellekthq";
      repo = "launchk";
      rev = "launchk-0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-j9ZU3owYtbKBG4rxZG7GyWymYsFSGR9OJSV+21KBq/A=";
    };
  };
  trzsz = {
    pname = "trzsz";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-go";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-CokZAXT61UKSsKnzE5mPMdAZecGX/8mgDkG4yDSat5M=";
    };
  };
  zashboard = {
    pname = "zashboard";
    version = "v3.5.0";
    src = fetchurl {
      url = "https://github.com/Zephyruso/zashboard/releases/download/v3.5.0/dist.zip";
      sha256 = "sha256-t3iKxz6Ko1by3p79nPTcPXuEIa+PWBFP4HrPn2y1N5Y=";
    };
  };
}
