# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cc-connect = {
    pname = "cc-connect";
    version = "v1.4.1";
    src = fetchFromGitHub {
      owner = "chenhg5";
      repo = "cc-connect";
      rev = "v1.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-Spm1OB0z7+E0JvWOtBAtUrRHiEc+aPjBYVHy0zc7ww4=";
    };
  };
  chrome-devtools-mcp = {
    pname = "chrome-devtools-mcp";
    version = "1.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/chrome-devtools-mcp/-/chrome-devtools-mcp-1.4.0.tgz";
      sha256 = "sha256-0tRNmnPaSZIILB8WhfvEoTaUF2cNSplI0w7L70FBmZk=";
    };
  };
  launchk = {
    pname = "launchk";
    version = "launchk-0.3.1";
    src = fetchFromGitHub {
      owner = "intellekthq";
      repo = "launchk";
      rev = "launchk-0.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-j9ZU3owYtbKBG4rxZG7GyWymYsFSGR9OJSV+21KBq/A=";
    };
  };
  trzsz = {
    pname = "trzsz";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "trzsz";
      repo = "trzsz-go";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-CokZAXT61UKSsKnzE5mPMdAZecGX/8mgDkG4yDSat5M=";
    };
  };
  voltagent-subagents = {
    pname = "voltagent-subagents";
    version = "5983fe3b4ea2785335ac1712c4aa1ac4e13a8fa2";
    src = fetchFromGitHub {
      owner = "VoltAgent";
      repo = "awesome-claude-code-subagents";
      rev = "5983fe3b4ea2785335ac1712c4aa1ac4e13a8fa2";
      fetchSubmodules = false;
      sha256 = "sha256-7XpsETQwB/yVfgZpeUWKPlt8cVCsp6ypj4EVyC1aqZ4=";
    };
  };
  zashboard = {
    pname = "zashboard";
    version = "v3.11.0";
    src = fetchurl {
      url = "https://github.com/Zephyruso/zashboard/releases/download/v3.11.0/dist.zip";
      sha256 = "sha256-pH0ZZtTflkh/8F8J4YlIKrgiUC8VchL6hy5JtgV/pYA=";
    };
  };
}
