---
version: "3"

includes:
  ss: ./Taskfile.ss.yml
  tcp: ./Taskfile.TCP.yml
  throughput: ./Taskfile.iperf.yml
  dns: ./Taskfile.DNS.yml
  ping: ./Taskfile.ping.yml
  ip: ./Taskfile.IP.yml
  fw: ./Taskfile.firewall.yml
  nmap: ./Taskfile.nmap.yml
  curl: ./Taskfile.curl.yml
  proxy: ./Taskfile.proxy.yml
